---
title: "Tourist Arrival"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# Data 

The data source is from wikipedia : https://en.wikipedia.org/wiki/Tourism_in_Nepal

# Load library

```{r}
library(ggplot2) # visualization
library(readr) # read data
```

# Read data

```{r}
arrivals <- read_csv("data/tourist_arrival.csv")
```

# Explore data

```{r}
head(arrivals)
```

```{r}
tail(arrivals)
```

```{r}
ggplot(arrivals, aes(x = year, y = tourist_arrival)) +
  geom_bar(stat = "identity") +
  labs(title = 'Yearly - Tourist Arrival in Nepal', 
       x = 'Year', y = 'Tourist Arrival') 
```

# Last 6 years Tourist Arrival

```{r}
ggplot(tail(arrivals), aes(year, tourist_arrival)) +
  geom_bar(stat = "identity") +
  labs(title = 'Yearly - Tourist Arrival in Nepal', 
       x = 'Year', y = 'Tourist Arrival') 
```

# Yearly Tourist Arrival in Nepal

```{r}
p <- ggplot(arrivals, aes(year, tourist_arrival)) +
  geom_line(color="blue") +
  expand_limits(y = c(0, NA)) +
  labs(title = 'Yearly - Tourist Arrival in Nepal', 
       x = 'Year', y = 'Tourist Arrival') 

p
```

# Set Limits of X-axis

```{r}
p + xlim(1995, 2020)
```








